Feature/test questions
1gory/vinokurov-tours pull request #1
Opened 2019-04-01 18:31 UTC by OrlovskyIvan

2019-04-01 18:36 UTC, OrlovskyIvan commented
Test comment

2019-04-01 19:56 UTC, 1gory requested changes

2019-04-01 19:56 UTC, 1gory commented on src/components/Button/index.jsx
> +const Button = (props) => {
`export default const  ( { text, width, handleClick }) =>  (
    <ButtonElem width={width} onClick={handleClick}>{text}</ButtonElem>
  )`

2019-04-01 19:56 UTC, 1gory commented on src/components/Logo/index.jsx
> +import airplane from '../../img/icons/baseline-airplanemode_active-24px.svg';
logo

2019-04-01 19:56 UTC, 1gory commented on src/containers/TestQuestionsForm/index.jsx
> +const TestQuestionsFormElem = styled.form`
...

2019-04-01 19:56 UTC, 1gory commented on src/containers/Input/index.jsx
> +    console.log(number.length);
...

2019-04-01 19:56 UTC, 1gory commented on src/containers/TestQuestionsOptions/index.jsx
> +      questionsData: [
Вынести

2019-04-01 19:56 UTC, 1gory commented on src/state/TestQuestionsImage.jsx
> +import test1 from '../img/1.jpg';
...

2019-04-01 19:56 UTC, 1gory commented on src/state/TestQuestionsState.jsx
> +    console.log(newObj);
...

2019-04-01 19:56 UTC, 1gory commented on src/state/TestQuestionsState.jsx
> +    // const formDataPhoneCollectred =
...

2019-04-01 19:56 UTC, 1gory commented on src/state/TestQuestionsState.jsx
> +    console.log(newTestQuestionData);
...

2019-04-01 19:56 UTC, 1gory commented on src/index.jsx
> +import { Provider } from 'unstated';
...

2019-04-01 19:56 UTC, 1gory commented on src/assets/style/fonts.css
> +
перенос

2019-04-01 20:02 UTC, 1gory commented
Что касается "html entities must be escaped", решим вопрос так: «ОТПРАВИТЬ» 🙃

2019-04-02 10:47 UTC, 1gory requested changes
1) Проверь, пожалуйста, ошибки npm run lint
2) Видимо, не так объяснил про названия. Question меняем на Step, Test на Quiz, то есть будет QuizStep вместо TestQuestion

2019-04-02 10:47 UTC, 1gory commented on src/containers/StepsOptions/index.jsx
> +const GoBack = styled.div`
Это же кнопка? Почему не button?

2019-04-02 10:47 UTC, 1gory commented on src/state/StepsState.jsx
> +export default StepsContainer;
Здесь и везде предлагаю писать `export default class extends Component`, чтобы было лаконичнее

2019-04-02 10:47 UTC, 1gory commented on src/state/StepsState.jsx
> +    const newObj = {};
tempObj

2019-04-02 10:47 UTC, 1gory commented on src/index.jsx
> +import { Provider } from 'unstated';
Тут не поправлено, у меня npm run lint показывает 13 ошибок, включая эту

2019-04-02 10:47 UTC, 1gory commented on src/containers/StepsForm/index.jsx
> +              <Button width={224} text="начать опрос заного" handleClick={goToFirstStepHandler} />
заново

2019-04-02 10:47 UTC, 1gory commented on src/containers/StepsForm/index.jsx
> +                Нажимая на кнопку "ОТПРАВИТЬ",
К ПР писал коммент, предлагал вместо кавычек использовать ёлочки

2019-04-02 10:47 UTC, 1gory commented on src/index.jsx
>  import 'normalize.css';
Давай нормалайзер отсюда выпилим, раз решили использовать другой

2019-04-02 10:47 UTC, 1gory commented on src/components/Logo/index.jsx
> +    <Title>ТурагенствоДмитрия Винокурова</Title>
Видимо, пробел потерялся

2019-04-02 10:47 UTC, 1gory commented on src/App.jsx
> +export const App = () => (
export default

2019-04-02 20:10 UTC, 1gory approved these changes

2019-04-02 20:10 UTC, merged